name: Snyk IaC Scan

description: "A reusable action to perform Snyk IaC scanning"

inputs:
  snyk_token:
    description: 'Snyk Token for authentication'
    required: true
  github_token:
    description: 'GitHub Token for pull request decoration'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
  
    - name: Install dependencies
      run: pip install subprocess-run
      shell: bash

    - name: Check for Terraform files
      id: terraform-check
      run: python scripts/check_terraform_files.py
      shell: bash

    - name: Set up Node.js
      if: steps.terraform-check.outputs.terraform_files_found == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '22.4.1'

    - name: Install Snyk CLI
      if: steps.terraform-check.outputs.terraform_files_found == 'true'
      run: npm install -g snyk
      shell: bash

    - name: Authenticate Snyk
      if: steps.terraform-check.outputs.terraform_files_found == 'true'
      env:
        SNYK_TOKEN: ${{ inputs.snyk_token }}
      run: snyk auth $SNYK_TOKEN
      shell: bash

    - name: Run Snyk Test
      id: snyk-test
      if: steps.terraform-check.outputs.terraform_files_found == 'true'
      run: |
        snyk iac test > snyk_output.txt || true
        echo "Snyk test output:"
        cat snyk_output.txt
        TEST_OUTPUT=$(cat snyk_output.txt)
        echo "SNYK_TEST_OUTPUT<<EOF" >> $GITHUB_ENV
        echo "${TEST_OUTPUT}" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        echo "Test output captured."
      shell: bash

    - name: Check if Snyk Test Output is Empty
      run: |
        if [ -z "${{ env.SNYK_TEST_OUTPUT }}" ]; then
          echo "Snyk test output is empty. Exiting."
          exit 1
        fi
      shell: bash

    - name: Use Pull Request Decoration Action
      if: ${{ env.SNYK_TEST_OUTPUT != '' }}
      uses: douglasmendeslda/gha-pull-request-decoration@v1.1
      with:
        message: ${{ env.SNYK_TEST_OUTPUT }}
      env:
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        GITHUB_REPOSITORY_NAME: ${{ github.event.pull_request.head.repo.name }}
        GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
