name: 'IaC Scan'
description: 'Verifies if there are any .tf files and runs snyk iac test if found'

inputs:
  snyk-token:
    description: 'Snyk API token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Check for .tf files'
      id: check_tf_files
      shell: bash
      run: |
        if git ls-files '*.tf' | grep -q .; then
          echo "found=true" >> $GITHUB_ENV
        else
          echo "found=false" >> $GITHUB_ENV
        fi

    - name: Set up Node.js
      if: env.found == 'true'
      shell: bash
      uses: actions/setup-node@v4
      with:
        node-version: '22.4.1'

    - name: Install Snyk CLI
      if: env.found == 'true'
      shell: bash
      run: npm install -g snyk

    - name: Authenticate Snyk
      if: env.found == 'true'
      shell: bash
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk auth $SNYK_TOKEN
    
    - name: 'Run Snyk IaC Test'
      if: env.found == 'true'
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
      run: |
          snyk iac test > snyk_output.txt || true
          echo "Snyk test output:"
          cat snyk_output.txt
          TEST_OUTPUT=$(cat snyk_output.txt)
          echo "SNYK_TEST_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "${TEST_OUTPUT}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "Test output captured."

      - name: Use Pull Request Decoration Action
        if: ${{ env.SNYK_TEST_OUTPUT != '' }}
        shell: bash
        uses: douglasmendeslda/gha-pull-request-decoration@v1.1
        with:
          message: ${{ env.SNYK_TEST_OUTPUT }}
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.pull_request.head.repo.name }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}