name: Snyk IaC Scan

description: "A reusable action to perform Snyk IaC scanning"

inputs:
  snyk_token:
    description: 'Snyk Token for authentication'
    required: true
  github_token:
    description: 'GitHub Token for pull request decoration'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout the action repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t gha-synk-scan:latest .
      shell: bash
    
    - name: Verify if Terraform check script exists
      run: |
        echo "Current directory: $(pwd)"
        echo "List files in current directory:"
        ls -l
        if [ ! -f scripts/check_terraform_files.py ]; then
          echo "The script scripts/check_terraform_files.py does not exist."
          exit 1
        fi
      shell: bash

    - name: Run Docker container
      run: docker run --rm gha-synk-scan:latest ${{ inputs.snyk_token }} ${{ inputs.github_token }}
      shell: bash
