name: Snyk IaC Scan

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  check-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
  
      - name: Install dependencies
        run: pip install subprocess-run

      - name: Check for Terraform files
        id: terraform-check
        run: python scripts/check_terraform_files.py

      - name: Set output
        id: set-output
        run: echo "::set-output name=terraform_files_found::${{ env.TERRAFORM_FILES_FOUND }}"

  snyk-iac-scan:
    runs-on: ubuntu-latest
    needs: check-terraform
    if: needs.check-terraform.outputs.terraform_files_found == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.4.1'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN
        
      - name: Run snyk Iac Scan
        run: snyk iac test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
